name: Bandit Analysis
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    name: Análisis de seguridad con Bandit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar Bandit
        run: pip install bandit[toml]

      - name: Ejecutar Bandit
        run: |
          bandit -r . -f json -o bandit-report.json
            if bandit -r . -f json | jq '.results[] | select(.issue_severity=="HIGH")' | grep -q .; then exit 1; fi

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-report
          path: bandit-report.json